on:
  push:
    branches:
      - main
      
jobs:
  deploy_to_dockerhub:
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and tag Docker images
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd:latest
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd:latest ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd:${{ github.run_number }}

      - name: Push images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd:${{ github.run_number }}