name: Docker Build and Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and tag Docker images
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd:${{ github.run_number }}

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push images to Docker Hub
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd:${{ github.run_number }}
