name: Docker Build and Deploy

on:
  push:
    branches:
      - main
jobs:
  build-container:
    name: build Docker container image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Push images to Docker Hub
      uses: docker/build-push-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }} 
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: cmhamdi/ci-cd 
        tags: latest, ${{ github.run_number }} 
